version: '3.3'

services:
  bookquiz-db:
    image: postgres:17-alpine
    container_name: bookquiz-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bookquiz_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - backend

networks:
  backend:
    driver: bridge
