CREATE TABLE authorities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE book_author
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE book_illustrator
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE book_translator
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    isbn        VARCHAR(30)                             NOT NULL,
    publisher   VARCHAR(255)                            NOT NULL,
    quiz_price  INTEGER                                 NOT NULL,
    thumbnail   VARCHAR(1000),
    max_attempt INTEGER                                 NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id BIGINT,
    book_id BIGINT,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE multiple_choice_options
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    option_text  VARCHAR(255)                            NOT NULL,
    option_index INTEGER                                 NOT NULL,
    quiz_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_multiple_choice_options PRIMARY KEY (id)
);

CREATE TABLE multiple_choice_quizzes
(
    id     BIGINT  NOT NULL,
    answer INTEGER NOT NULL,
    CONSTRAINT pk_multiple_choice_quizzes PRIMARY KEY (id)
);

CREATE TABLE multiple_choice_user_answers
(
    id          BIGINT  NOT NULL,
    user_answer INTEGER NOT NULL,
    CONSTRAINT pk_multiple_choice_user_answers PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id UUID,
    book_id  BIGINT,
    price    INTEGER                                 NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           UUID                        NOT NULL,
    username     VARCHAR(50)                 NOT NULL,
    order_status ORDER_STATUS_ENUM           NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE quizzes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quiz_type   VARCHAR(31)                             NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    explanation VARCHAR(255),
    hint        VARCHAR(255),
    book_id     BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_quizzes PRIMARY KEY (id)
);

CREATE TABLE subjective_quizzes
(
    id     BIGINT NOT NULL,
    answer TEXT   NOT NULL,
    CONSTRAINT pk_subjective_quizzes PRIMARY KEY (id)
);

CREATE TABLE subjective_user_answers
(
    id          BIGINT NOT NULL,
    user_answer TEXT   NOT NULL,
    CONSTRAINT pk_subjective_user_answers PRIMARY KEY (id)
);

CREATE TABLE toss_payments
(
    id           UUID                        NOT NULL,
    payment_key  VARCHAR(255)                NOT NULL,
    order_id     UUID                        NOT NULL,
    amount       BIGINT                      NOT NULL,
    method       VARCHAR(255)                NOT NULL,
    status       VARCHAR(255)                NOT NULL,
    type         VARCHAR(255)                NOT NULL,
    requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    approved_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_toss_payments PRIMARY KEY (id)
);

CREATE TABLE true_false_quizzes
(
    id     BIGINT  NOT NULL,
    answer BOOLEAN NOT NULL,
    CONSTRAINT pk_true_false_quizzes PRIMARY KEY (id)
);

CREATE TABLE true_false_user_answers
(
    id          BIGINT  NOT NULL,
    user_answer BOOLEAN NOT NULL,
    CONSTRAINT pk_true_false_user_answers PRIMARY KEY (id)
);

CREATE TABLE user_answers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer_type    VARCHAR(31)                             NOT NULL,
    user_id        VARCHAR(50)                             NOT NULL,
    quiz_id        BIGINT                                  NOT NULL,
    attempt_number INTEGER                                 NOT NULL,
    is_correct     BOOLEAN                                 NOT NULL,
    answered_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_answers PRIMARY KEY (id)
);

CREATE TABLE user_authorities
(
    authority_id BIGINT      NOT NULL,
    username     VARCHAR(50) NOT NULL,
    CONSTRAINT pk_user_authorities PRIMARY KEY (authority_id, username)
);

CREATE TABLE user_books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(50)                             NOT NULL,
    book_id          BIGINT                                  NOT NULL,
    order_id         UUID,
    max_attempts     INTEGER                                 NOT NULL,
    current_attempts INTEGER                                 NOT NULL,
    owned_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_books PRIMARY KEY (id)
);

CREATE TABLE users
(
    username      VARCHAR(50)                 NOT NULL,
    name          VARCHAR(64)                 NOT NULL,
    password      VARCHAR(255)                NOT NULL,
    email         VARCHAR(255)                NOT NULL,
    phone_number  VARCHAR(20)                 NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    province      PROVINCE_ENUM               NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    grade         GRADE_ENUM                  NOT NULL,
    enabled       BOOLEAN                     NOT NULL,
    gender        BOOLEAN                     NOT NULL,
    refresh_token VARCHAR(1000),
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE authorities
    ADD CONSTRAINT uc_authorities_name UNIQUE (name);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE persons
    ADD CONSTRAINT uc_persons_name UNIQUE (name);

ALTER TABLE toss_payments
    ADD CONSTRAINT uc_toss_payments_order UNIQUE (order_id);

ALTER TABLE toss_payments
    ADD CONSTRAINT uc_toss_payments_payment_key UNIQUE (payment_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE user_answers
    ADD CONSTRAINT user_quiz_attempt_unique UNIQUE (user_id, quiz_id, attempt_number);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE multiple_choice_options
    ADD CONSTRAINT FK_MULTIPLE_CHOICE_OPTIONS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES multiple_choice_quizzes (id);

ALTER TABLE multiple_choice_quizzes
    ADD CONSTRAINT FK_MULTIPLE_CHOICE_QUIZZES_ON_ID FOREIGN KEY (id) REFERENCES quizzes (id);

ALTER TABLE multiple_choice_user_answers
    ADD CONSTRAINT FK_MULTIPLE_CHOICE_USER_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES user_answers (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE quizzes
    ADD CONSTRAINT FK_QUIZZES_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE subjective_quizzes
    ADD CONSTRAINT FK_SUBJECTIVE_QUIZZES_ON_ID FOREIGN KEY (id) REFERENCES quizzes (id);

ALTER TABLE subjective_user_answers
    ADD CONSTRAINT FK_SUBJECTIVE_USER_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES user_answers (id);

ALTER TABLE toss_payments
    ADD CONSTRAINT FK_TOSS_PAYMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE true_false_quizzes
    ADD CONSTRAINT FK_TRUE_FALSE_QUIZZES_ON_ID FOREIGN KEY (id) REFERENCES quizzes (id);

ALTER TABLE true_false_user_answers
    ADD CONSTRAINT FK_TRUE_FALSE_USER_ANSWERS_ON_ID FOREIGN KEY (id) REFERENCES user_answers (id);

ALTER TABLE user_answers
    ADD CONSTRAINT FK_USER_ANSWERS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE user_answers
    ADD CONSTRAINT FK_USER_ANSWERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (username);

ALTER TABLE user_books
    ADD CONSTRAINT FK_USER_BOOKS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE user_books
    ADD CONSTRAINT FK_USER_BOOKS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE user_books
    ADD CONSTRAINT FK_USER_BOOKS_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE book_illustrator
    ADD CONSTRAINT fk_booill_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_illustrator
    ADD CONSTRAINT fk_booill_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE book_translator
    ADD CONSTRAINT fk_bootra_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_translator
    ADD CONSTRAINT fk_bootra_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE user_authorities
    ADD CONSTRAINT fk_useaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id);

ALTER TABLE user_authorities
    ADD CONSTRAINT fk_useaut_on_user FOREIGN KEY (username) REFERENCES users (username);
