CREATE TYPE grade_enum AS ENUM (
    'AGE_5',
    'AGE_6',
    'AGE_7',
    'ELEMENTARY_1',
    'ELEMENTARY_2',
    'ELEMENTARY_3',
    'ELEMENTARY_4',
    'ELEMENTARY_5',
    'ELEMENTARY_6',
    'MIDDLE_1',
    'MIDDLE_2',
    'MIDDLE_3',
    'HIGH_1',
    'HIGH_2',
    'HIGH_3',
    'COLLEGE_GENERAL'
    );
CREATE TYPE province_enum AS ENUM (
    'SEOUL',
    'BUSAN',
    'DAEJEON',
    'DAEGU',
    'GWANGJU',
    'INCHEON',
    'ULSAN',
    'GYEONGGI',
    'GANGWON',
    'CHUNGBUK',
    'CHUNGNAM',
    'JEONBUK',
    'JEONNAM',
    'GYEONGBUK',
    'GYEONGNAM',
    'JEJU',
    'ETC_OVERSEAS'
    );

CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255)                            NOT NULL,
    username  VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE users
(
    username      VARCHAR(50)                 NOT NULL,
    name          VARCHAR(64)                 NOT NULL,
    password      VARCHAR(255)                NOT NULL,
    email         VARCHAR(255)                NOT NULL,
    phone_number  VARCHAR(20)                 NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    province      PROVINCE_ENUM               NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    grade         GRADE_ENUM                  NOT NULL,
    enabled       BOOLEAN                     NOT NULL,
    gender        BOOLEAN                     NOT NULL,
    refresh_token VARCHAR(1000),
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE authorities
    ADD CONSTRAINT uc_05d4aeb21a68f66f67e6a2187 UNIQUE (username, authority);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);
