CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255)                            NOT NULL,
    username  VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

ALTER TABLE users
    ADD enabled BOOLEAN;

ALTER TABLE users
    ADD username VARCHAR(50);

ALTER TABLE users
    ALTER COLUMN enabled SET NOT NULL;

ALTER TABLE authorities
    ADD CONSTRAINT uc_05d4aeb21a68f66f67e6a2187 UNIQUE (username, authority);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);

ALTER TABLE users
    DROP COLUMN user_id;

ALTER TABLE users
    DROP COLUMN banned;

ALTER TABLE users
    ALTER COLUMN name TYPE VARCHAR(64) USING (name::VARCHAR(64));

ALTER TABLE users
    ALTER COLUMN password TYPE VARCHAR(255) USING (password::VARCHAR(255));

ALTER TABLE users
    ADD CONSTRAINT pk_users PRIMARY KEY (username);
