CREATE TYPE grade_enum AS ENUM (
    'AGE_5',
    'AGE_6',
    'AGE_7',
    'ELEMENTARY_1',
    'ELEMENTARY_2',
    'ELEMENTARY_3',
    'ELEMENTARY_4',
    'ELEMENTARY_5',
    'ELEMENTARY_6',
    'MIDDLE_1',
    'MIDDLE_2',
    'MIDDLE_3',
    'HIGH_1',
    'HIGH_2',
    'HIGH_3',
    'COLLEGE_GENERAL'
    );
CREATE TYPE province_enum AS ENUM (
    'SEOUL',
    'BUSAN',
    'DAEJEON',
    'DAEGU',
    'GWANGJU',
    'INCHEON',
    'ULSAN',
    'GYEONGGI',
    'GANGWON',
    'CHUNGBUK',
    'CHUNGNAM',
    'JEONBUK',
    'JEONNAM',
    'GYEONGBUK',
    'GYEONGNAM',
    'JEJU',
    'ETC_OVERSEAS'
    );

CREATE TYPE order_status_enum AS ENUM (
    'PENDING',
    'PROCESSING',
    'COMPLETED',
    'CANCELED',
    'REFUNDED',
    'CONFIRMED'
    );

CREATE TABLE authorities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE book_author
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE book_illustrator
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE book_translator
(
    book_id   BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE books
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    isbn       VARCHAR(30)                             NOT NULL,
    publisher  VARCHAR(255)                            NOT NULL,
    quiz_price INTEGER                                 NOT NULL,
    thumbnail  VARCHAR(1000),
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id BIGINT,
    book_id BIGINT,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT,
    book_id  BIGINT,
    price    INTEGER                                 NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    order_status ORDER_STATUS_ENUM                       NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE user_authorities
(
    authority_id BIGINT      NOT NULL,
    username     VARCHAR(50) NOT NULL,
    CONSTRAINT pk_user_authorities PRIMARY KEY (authority_id, username)
);

CREATE TABLE users
(
    username      VARCHAR(50)                 NOT NULL,
    name          VARCHAR(64)                 NOT NULL,
    password      VARCHAR(255)                NOT NULL,
    email         VARCHAR(255)                NOT NULL,
    phone_number  VARCHAR(20)                 NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    province      PROVINCE_ENUM               NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    grade         GRADE_ENUM                  NOT NULL,
    enabled       BOOLEAN                     NOT NULL,
    gender        BOOLEAN                     NOT NULL,
    refresh_token VARCHAR(1000),
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE authorities
    ADD CONSTRAINT uc_authorities_name UNIQUE (name);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE persons
    ADD CONSTRAINT uc_persons_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE book_illustrator
    ADD CONSTRAINT fk_booill_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_illustrator
    ADD CONSTRAINT fk_booill_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE book_translator
    ADD CONSTRAINT fk_bootra_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_translator
    ADD CONSTRAINT fk_bootra_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE user_authorities
    ADD CONSTRAINT fk_useaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id);

ALTER TABLE user_authorities
    ADD CONSTRAINT fk_useaut_on_user FOREIGN KEY (username) REFERENCES users (username);
