CREATE TYPE grade_enum AS ENUM (
  'AGE_5',
  'AGE_6',
  'AGE_7',
  'ELEMENTARY_1',
  'ELEMENTARY_2',
  'ELEMENTARY_3',
  'ELEMENTARY_4',
  'ELEMENTARY_5',
  'ELEMENTARY_6',
  'MIDDLE_1',
  'MIDDLE_2',
  'MIDDLE_3',
  'HIGH_1',
  'HIGH_2',
  'HIGH_3',
  'COLLEGE_GENERAL'
);
ALTER TABLE users
ADD COLUMN grade grade_enum NOT NULL
